Create CONTRIBUTING.md
elementary/wingpanel pull request #461
Opened 2022-07-14 22:09 UTC by danrabbit

2022-07-15 07:45 UTC, jeremypw requested changes
There is some inconsistency in the usage of "Wingpanel", "WingPanel" and "wingpanel".  The common name of the app according to `README.md` is "Wingpanel".

2022-08-08 19:35 UTC, danrabbit commented
Ah yeah copy paste errors for sure. Thanks for pointing it out!

2022-08-08 21:04 UTC, jeremypw requested changes
There is still a "wingpanel" in line 5.

2022-08-08 21:07 UTC, jeremypw approved these changes

2022-08-08 21:07 UTC, merged