Port to GTK4
elementary/wingpanel pull request #579
Opened 2024-09-17 16:52 UTC by leolost2605

2024-09-18 16:22 UTC, danirabbit commented
I think probably the best way forward for development is I can create a new packaging branch based on this branch and then build that in daily so we can start building indicators against it etc

But I'm not sure what trying to upgrade this mid-cycle looks like, so I'd like to leave it unmerged for now until we have a plan around how to handle the packaging/upgrade.

2024-09-18 23:09 UTC, danirabbit requested changes
Don't forget to update deps on README and .github :)

2024-09-19 17:52 UTC, danirabbit commented
There's a packaging branch now: https://github.com/elementary/wingpanel/tree/deb-packaging-gtk4

So we should have access to the library on OS 8 daily no problem to work with porting the other indicators when this builds: https://code.launchpad.net/~elementary-os/+recipe/wingpanel-8-daily

You might want to temporarily change the meson project name here to `io.elementary.wingpanel-8` or something so that you can install them both at the same time for testing? Otherwise the `io.elementary.wingpanel-8` package will refuse to install because of the file conflicts. But this package name will eventually be reverted anyways so that's optional I guess :woman_shrugging:

2025-04-17 23:16 UTC, danirabbit commented
Looks like we didn't properly update the library stuff so we could at least try to build indicators:
```
 trying to overwrite '/usr/include/wingpanel/wingpanel.h', which is also in package libwingpanel-dev 8.0.3+r719+pkg73~daily~ubu
ntu8.1
```

2025-04-17 23:20 UTC, danirabbit requested changes

2025-04-17 23:20 UTC, danirabbit commented on src/Widgets/IndicatorEntry.vala
> +public class Wingpanel.Widgets.IndicatorEntry : Gtk.Widget {
We should use Granite.Bin now I suppose

2025-04-17 23:20 UTC, danirabbit commented on src/Widgets/Panel.vala
> +public class Wingpanel.Widgets.Panel : Gtk.Widget {
Also bin here

2025-04-17 23:20 UTC, danirabbit commented on src/Widgets/Panel.vala
> +        //  window.get_display ().get_default_seat ().ungrab ();
Commented code?

2025-04-18 11:04 UTC, leolost2605 commented
> Looks like we didn't properly update the library stuff so we could at least try to build indicators:
> trying to overwrite '/usr/include/wingpanel/wingpanel.h', which is also in package libwingpanel-dev 8.0.3+r719+pkg73~daily~ubu
ntu8.1

@danirabbit I did something in #605 lmk if that's right :)

2025-04-22 00:10 UTC, danirabbit commented
I wonder if we should add this widget from Tasks since we have to replace ModelButton in a few places:

```
public class PopoverMenuitem : Gtk.Button {
    public string text {
        set {
            child = new Granite.AccelLabel (value) {
                action_name = this.action_name
            };

            update_property (Gtk.AccessibleProperty.LABEL, value, -1);
        }
    }

    class construct {
        set_css_name ("modelbutton");
    }

    construct {
        accessible_role = MENU_ITEM;

        clicked.connect (() => {
            var popover = (Gtk.Popover) get_ancestor (typeof (Gtk.Popover));
            if (popover != null) {
                popover.popdown ();
            }
        });
    }
}
```

2025-06-06 19:14 UTC, danirabbit commented
Finally starting to test this! It looks like we've got some issues with
- [ ] Indicators losing focus
- [ ] The panel not being transparent when it should be. Changing the wallpaper sets it correctly but then if you switch workspaces for example it'll go back to being opaque

![Screenshot from 2025-06-06 12 12 44](https://github.com/user-attachments/assets/aefcf760-dfc4-4e6e-ad47-8d9b4e21d095)

2025-06-07 16:54 UTC, danirabbit commented
Interestingly, I can't reproduce the issue with indicators closing without accepting clicks on my Starlite running at 1.5x scaling. So I wonder if it has to do with scaling somehow?

2026-01-13 16:26 UTC, danirabbit commented
@leolost2605 can you resolve merge conflicts here?

Since we're dropping X11 in OS 9, I'm not worried about any X11 bugs here. We could drop X11 in master before merging this if it makes it easier. Or we could drop it in a commit after merging this. Happy either way!

2026-02-18 19:02 UTC, danirabbit commented
I want to get this going. I'm fine with broken X support because we have to remove that anyways. Proposed the companion packaging branch here: https://github.com/elementary/wingpanel/pull/667

Dailies for wingpanel are only building for resolute now: https://code.launchpad.net/~elementary-os/+recipe/wingpanel-daily

2026-02-18 19:02 UTC, danirabbit approved these changes

2026-02-19 16:50 UTC, merged

2026-03-25 10:18 UTC, leolost2605 commented
> Finally starting to test this! It looks like we've got some issues with
> 
>     * [ ]  Indicators losing focus
> 
>     * [ ]  The panel not being transparent when it should be. Changing the wallpaper sets it correctly but then if you switch workspaces for example it'll go back to being opaque
> 
>     * [ ]  Clicking inside an indicator closes that indicator and clicks on buttons etc aren't accepted

@danirabbit can you still reproduce these? I can't reproduce any of them

2026-03-27 04:06 UTC, danirabbit commented
@leolost2605 im still experiencing some issues where the panel is always using the translucent style and never the transparent style, but it was working correctly for me at one point. So I'm thinking this is maybe a problem with my local installation. I'll file a new issue report if I can reproduce it on a clean install.

Thanks for fixing the issue with indicators not opening with the margins etc!

2026-04-01 12:43 UTC, decathorpe commented
It looks like this changed the library name to `libwingpanel-9` but (accidentally?) left the version-based soname  in place. So it results in a library called `libwingpanel-9.so.8.0.4` now, but would immediately bump to `libwingpanel-9.so.9.0.0` (a breaking change) when 9.0.0 is tagged. Looks like this should now be using a hard-coded (i.e. not version-based) soname instead so it doesn't accidentally change when 9.0.0 is released.